name: login-e2e-test

on:
  workflow_run:
    workflows: [signup-e2e-test]
    types:
      - completed

jobs:
  login:
    name: 'Execute sign up e2e flow'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Artifact-1
        uses: actions/download-artifact@master
        with:
          name: accounts.json
          path: accounts.json
      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 16.3.0
          cache: 'npm'
      - run: k6 run src/script.ts
