name: signup-e2e-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.3.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.3.0
          cache: 'npm'
      - run: mv data.json accounts.json
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: accounts.json
          path: accounts.json
