name: signup-e2e-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: mv data.json accounts.json
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: accounts.json
          path: accounts.json
